import fs from "fs";
import path from "path";
import { createRequire } from "module";
import type { Plugin } from "vite";
import type { PreloadManifestEntry } from "./types";

const nodeRequire = createRequire(path.join(process.cwd(), "/"));

/**
 * Vite plugin that injects `<link rel="preload">` tags for font files
 * listed in the preload manifest generated by `@gamesome/style-dictionary-font`.
 *
 * The manifest contains package paths (e.g. `@fontsource-variable/rubik/files/...`)
 * which this plugin resolves to URLs the browser can fetch.
 */
export function fontPreloadPlugin(manifestPath: string): Plugin {
	let base = "/";

	return {
		name: "gamesome-font-preload",
		configResolved(config) {
			base = config.base;
		},
		transformIndexHtml: {
			order: "post",
			handler(_html, ctx) {
				if (!fs.existsSync(manifestPath)) return [];

				const manifest: PreloadManifestEntry[] = JSON.parse(
					fs.readFileSync(manifestPath, "utf-8"),
				);

				const isDev = ctx.server !== undefined;

				return manifest.map((entry) => {
					let href: string;

					if (isDev) {
						// In dev mode, resolve to absolute file path and use Vite's /@fs/ prefix
						const resolved = nodeRequire.resolve(entry.href);
						href = `/@fs${resolved}`;
					} else {
						// In build mode, find the hashed asset in the bundle
						const fontFileName = path.basename(entry.href);
						const baseName = fontFileName.replace(/\.[^.]+$/, "");
						let assetUrl: string | undefined;

						if (ctx.bundle) {
							for (const [fileName] of Object.entries(ctx.bundle)) {
								if (fileName.includes(baseName)) {
									assetUrl = base + fileName;
									break;
								}
							}
						}

						href = assetUrl ?? entry.href;
					}

					return {
						tag: "link",
						attrs: {
							rel: entry.rel,
							as: entry.as,
							type: entry.type,
							crossorigin: entry.crossorigin,
							href,
						},
						injectTo: "head" as const,
					};
				});
			},
		},
	};
}
