import fs from "fs";
import path from "path";
import { createRequire } from "module";
import type { Plugin } from "vite";
import type { PreloadManifestEntry } from "./types";

const nodeRequire = createRequire(path.join(process.cwd(), "/"));

const regexEscape = (value: string) =>
	value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");

/**
 * Vite plugin that injects `<link rel="preload">` tags for font files
 * listed in the preload manifest generated by `@gamesome/style-dictionary-font`.
 *
 * The manifest contains package paths (e.g. `@fontsource-variable/rubik/files/...`)
 * which this plugin resolves to URLs the browser can fetch.
 */
export function fontPreloadPlugin(manifestPath: string): Plugin {
	let base = "/";

	return {
		name: "gamesome-font-preload",
		configResolved(config) {
			base = config.base;
		},
		transformIndexHtml: {
			order: "post",
			handler(_html, ctx) {
				if (!fs.existsSync(manifestPath)) return [];

				const manifest: PreloadManifestEntry[] = JSON.parse(
					fs.readFileSync(manifestPath, "utf-8")
				);

				const isDev = ctx.server !== undefined;

				return manifest.flatMap((entry) => {
					let href: string;

					if (isDev) {
						// In dev mode, resolve to absolute file path and use Vite's /@fs/ prefix
						const resolved = nodeRequire.resolve(entry.href);
						href = `/@fs${resolved}`;
					} else {
						// In build mode, find the hashed asset in the bundle by exact stem + extension match.
						const fontFileName = path.basename(entry.href);
						const extension = path.extname(fontFileName);
						const baseName = fontFileName.slice(0, -extension.length);
						const filePattern = new RegExp(
							`(?:^|/)${regexEscape(baseName)}(?:-[A-Za-z0-9_-]+)?${regexEscape(
								extension
							)}$`
						);
						let assetUrl: string | undefined;

						if (ctx.bundle) {
							for (const [fileName] of Object.entries(ctx.bundle)) {
								if (filePattern.test(fileName)) {
									assetUrl = base + fileName;
									break;
								}
							}
						}

						if (!assetUrl) {
							return [];
						}

						href = assetUrl;
					}

					return [
						{
							tag: "link",
							attrs: {
								rel: entry.rel,
								as: entry.as,
								type: entry.type,
								crossorigin: entry.crossorigin,
								href,
							},
							injectTo: "head" as const,
						},
					];
				});
			},
		},
	};
}
